=pod

=encoding UTF-8

=head1 NAME

Statistics::NiceR - interface to the R programming language

=head1 VERSION

version 0.01

=head1 SYNOPSIS

=head1 METHODS

=head2 new

  new()

Creates a new instance of a wrapper around the R interpreter.

   use Statistics::NiceR
   my $r = Statistics::NiceR->new();

=head2 eval_parse

   $eval_result = eval_parse( Str $r_code )

A convenience function that allows for evaluating arbitrary R code.

The return value is the last line of the code in C<$r_code>.

=head1 CALLING R FUNCTIONS

=head1

=head1 AUTHOR

Zakariyya Mughal <zmughal@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2014 by Zakariyya Mughal.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
